project:
  type: book
  output-dir: build
  preview: 
    port: 3000
    browser: false

toc: true
toc-depth: 4
number-sections: true
number-depth: 3

book:
  title: "CompOrg at NCKU EE"
  author: 
    - name: "Chun-Hao Chang"
      email: "q18131500@gs.ncku.edu.tw"
      affiliations:
        - name: "National Cheng Kung University"
  page-navigation: true
  site-url: https://computer-organization-at-ncku-ee.github.io/lab-documents/ 
  repo-url: https://github.com/Computer-Organization-at-NCKU-EE/lab-documents 
  navbar:
    background: primary
    search: true
  sidebar:
    style: docked
    collapse-level: 1
  # downloads: pdf
  output-file: "book"
  chapters:
    - index.qmd
    # Lab 1
    - part: book/lab-1/index.qmd
      chapters:
        - book/lab-1/computer.qmd
        - book/lab-1/riscv.qmd
        - book/lab-1/iss.qmd
    # Lab 2
    - part: book/lab-2/index.qmd
      chapters:
        - book/lab-2/riscv-asm.qmd
        - book/lab-2/bare-metal.qmd
    # Lab 3
    - part: book/lab-3/index.qmd
      chapters: 
        - book/lab-3/single-cycle-cpu.qmd
        - book/lab-3/cross-verify.qmd
    # Lab 4
    - part: book/lab-4/index.qmd
      chapters: 
        - book/lab-4/pipeline-basic.qmd
        - book/lab-4/pipeline-microarch.qmd
    # Lab 5
    - part: book/lab-5/index.qmd
      chapters: 
        - book/lab-5/locality.qmd
        - book/lab-5/cache.qmd
    # Lab 6
    - part: book/lab-6/index.qmd
      chapters:
        - book/lab-6/dram.qmd
        - book/lab-6/dpi-wrapper.qmd
    # Overall References
    - ref.qmd
  appendices: 
    # C Programming Review
    - part: book/appendix/c-prog/index.qmd
      chapters:
        - book/appendix/c-prog/pointer.qmd
        - book/appendix/c-prog/oop-in-c.qmd
    # On-Chip System Bus Protocol
    - part: book/appendix/bus/index.qmd
      chapters: 
        - book/appendix/bus/axi-basics.qmd
        - book/appendix/bus/axi-impl.qmd
        - book/appendix/bus/wrapper.qmd
    # RTL Programming Concepts
    - part: book/appendix/rtl/index.qmd
      chapters: 
        - book/appendix/rtl/verilog.qmd
        - book/appendix/rtl/sv.qmd
        - book/appendix/rtl/sva.qmd
    # Others
    - book/appendix/basic-linux.qmd
    - book/appendix/git.qmd
    - book/appendix/docker.qmd 

csl: ieee.csl

bibliography:
  - book/lab-1/ref.bib
  - book/lab-2/ref.bib
  - book/lab-3/ref.bib
  - book/lab-4/ref.bib
  - book/lab-5/ref.bib
  - book/lab-6/ref.bib
  - book/appendix/ref.bib
  - book/appendix/c-prog/ref.bib
  - book/appendix/bus/ref.bib
  - book/appendix/rtl/ref.bib

format:
  html:
    theme:
      - zephyr
    toc: true
    toc-expand: true
    code-annotations: true
    code-copy: true
    code-line-numbers: true
  # pdf:
    # pdf-engine: xelatex
    # documentclass: scrreprt
    # papersize: a4paper
    # lof: true
    # lot: true
    # fontsize: "12"
    # CJKmainfont: "KaiTi"
    # link-citations: true
    # link-bibliography: true
