on:
  push:
    branches:
      - main
name: Render and Publish
# you need these permissions to publish to GitHub pages
permissions: 
    contents: write
    pages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
